[package]
name = "ta"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
clap = { version = "4.1.6", features = ["derive"] }
crossterm = "0.26.0"
tmux_interface = "0.2.1"
tui = "0.19.0"
unicode-width = "0.1.10"
